# Generated by Django 3.1.3 on 2022-07-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choiceText',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionText',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionMark',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_mark',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
