# Generated by Django 3.1.3 on 2022-07-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220720_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_mark',
            new_name='question_grade',
        ),
    ]
